version: '3.5'

services:
  redis:
      image: redis
      restart: unless-stopped
      ports:
        - "6379:6379"
  db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=admin
        - PGPASSWORD=admin
  nginx:
      image: nginx
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
      build: ./frontend-example-docker
      expose:
        - "5000"
      environment: 
        - API_URL=http://backend:8000
      container_name: frontend_example
      depends_on:
        - backend
  backend:
      build: ./backend-example-docker
      links:
        - redis
        - db
      expose:
        - "8000"
      environment:
        - FRONT_URL=http://frontend:5000
        - REDIS=redis
        - DB_USERNAME=admin
        - DB_PASSWORD=admin
        - DB_HOST=db
      container_name: backend-example
